# Identificación única del proyecto en tu servidor
sonar.projectKey=certificados_firma-electronica365-backend_e7e50dea-3717-4e90-a8cc-e282b23d9ca9
sonar.projectName=firma-electronica365-backend
sonar.qualitygate.wait=true

# Ruta del código fuente
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Exclusiones cruciales para NestJS
sonar.exclusions=node_modules/**, dist/**, **/*.spec.ts, **/*.module.ts, main.ts